version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g npm@latest
      - npm install -g snyk
      - curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
  pre_build:
    commands:
      - npm install
  dependency_scan:
    commands:
      - snyk auth $SNYK_TOKEN
      - snyk test
  sast_secret_scan:
    commands:
      - bearer scan .
      - bearer scan . --scanner=secrets
  post_build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
artifacts:
  files:
    - '**/*'
  discard-paths: yes
