version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "$DOCKER_PWD" | docker login --username xwindwolf --password-stdin
      - npm install -g npm@latest
      - npm install -g snyk
      - curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
  pre_build:
    on-failure: continue
    commands:
      - npm install
      #- snyk auth $SNYK_TOKEN
      #- snyk test
  build:
    on-failure: continue
    commands:
      #- ./bin/bearer scan . --exit-code 0
      #- ./bin/bearer scan . --scanner=secrets --exit-code 0
  post_build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker image push -a $REPOSITORY_URI
artifacts:
  files:
    - '**/*'
  discard-paths: yes
